image: docker:latest
services:
  - docker:dind
stages:
  - build
  - test
  - deploy
  - release
variables:
    DOCKER_IMAGE_NAME: "nginx-ci"
    DOCKER_IMAGE_TAG: "20170817"
                        
before_script:
  - docker info
build:
  stage: build      
  script:
    - docker build . -t registry.gitlab.com/$DOCKER_USER/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/$DOCKER_USER/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
test:
  stage: test
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/$DOCKER_USER/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker network create wrktest
    - docker run -d -p 80:80 --name app --network wrktest registry.gitlab.com/$DOCKER_USER/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - sleep 5
    - docker run --name wrk --network wrktest --rm williamyeh/wrk -t2 -c5 -d5s --timeout 2s http://app/ > test/result.txt
    - apk add --update bash bc
    - cd test && cat result.txt && ./test.sh
deploy:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/$DOCKER_USER/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker tag registry.gitlab.com/$DOCKER_USER/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $DOCKER_USER/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker push $DOCKER_USER/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
release:
  stage: release
  script:
    - docker pull azuresdk/azure-cli-python:0.2.8
    - docker run -t --rm -v $(pwd)/release.sh:/release.sh -e AZURE_LOGIN_USER=$AZURE_LOGIN_USER -e AZURE_PASSWORD=$AZURE_PASSWORD -e AZURE_TENANT=$AZURE_TENANT -e DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME -e DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG -e DOCKER_USER=$DOCKER_USER azuresdk/azure-cli-python:0.2.8 /release.sh
